### ISSUE TITLE
Showcase images broke on index.html

### ISSUE THREAD

**Issue by brianzelip** [basscss/basscss.github.io#5]
The 4 showcase screenshots on the bass docs home page are broken. (the built html is all pre routed in advanced ways now that i'm not sure where the problem is, would love to find out though to be able to make sense of how ur building the site. it's pretty crazy :)  )

**Comment by jxnblk** [comment]
Hey, thanks for pointing this out! It looks like I went cavalier and renamed the key for the asset path here: https://github.com/basscss/showcase/blob/gh-pages/data.js#L12 which broke things here https://github.com/basscss/basscss.github.io/blob/master/components/Showcase.jsx#L11

If you wanna take a stab at it, I think you'd only need to change the second file. Otherwise I'll push a fix later today.

**Comment by brianzelip** [comment]
Thx, i'll break my machine out after my next meeting and followup.

**Comment by brianzelip** [comment]
Given the two highlighted lines from your above links, the only thing I can think to change is [this line](https://github.com/basscss/basscss.github.io/blob/master/components/Showcase.jsx#L1) from:

``` javascript
let assetPath = this.props.asset_path
```

to:

``` javascript
let assetPath = this.props.cdn
```

I tried to build the site locally after forking then cloning to local, but got lots of errors early on at `$ npm install`, so I can't test to see if the change above works so as to warrant a PR.

**Comment by brianzelip** [comment]
yeah, now that I see from the published online docs source that there is no URL present for the images, and that the history of `data.js` used to include this line:

``` javascript
data.asset_path = 'http://d2v52k3cl9vedd.cloudfront.net/basscss/assets/';
```

I'm pretty sure the fix is what I said earlier. Without testing it, I'll just offer a PR, and you can accept it if it's correct.

**Comment by jxnblk** [comment]
Yup, that looks right. I'll pull down the PR and make sure it builds.
